name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repository
        uses: actions/checkout@v3
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze --fatal-infos
      - name: Format
        run: dart format -o none --set-exit-if-changed .
      - name: Test
        run: dart test
